# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-20 12:32


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_scenario_mds_allow_partial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
