# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0027_auto_20181121_1500'),
        ('stats', '0009_auto_20180620_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='focus_sets',
            field=models.ManyToManyField(blank=True, to='annotations.FocusSet'),
        ),
    ]
