# Generated by Django 2.2.6 on 2019-11-21 17:17

import django.core.validators
from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_auto_20190213_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='formal_structure',
            field=models.PositiveIntegerField(choices=[(0, 'none'), (1, 'narration'), (2, 'dialogue')], default=0, verbose_name='Formal structure'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='formal_structure_strict',
            field=models.BooleanField(default=True, verbose_name='Require translations to be in the same formal structure'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='is_test',
            field=models.BooleanField(default=False, help_text='Checking this box signals that the scenario should not be displayed in the standard overview.', verbose_name='Test scenario'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='mds_allow_partial',
            field=models.BooleanField(default=False, help_text='When enabled, the model will include tuples where one or more of the target languages have no Annotation', verbose_name='Allow partial tuples in model'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='mds_dimensions',
            field=models.PositiveIntegerField(default=5, help_text='Number of dimensions to use in Multidimensional Scaling. Should be between 2 and 5.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)], verbose_name='Number of dimensions'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='mds_fragments',
            field=picklefield.fields.PickledObjectField(editable=False, null=True, verbose_name='MDS fragments'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='mds_labels',
            field=picklefield.fields.PickledObjectField(editable=False, null=True, verbose_name='MDS labels'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='mds_matrix',
            field=picklefield.fields.PickledObjectField(editable=False, null=True, verbose_name='MDS matrix'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='mds_model',
            field=picklefield.fields.PickledObjectField(editable=False, null=True, verbose_name='MDS model'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='mds_stress',
            field=models.FloatField(null=True, verbose_name='MDS stress'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='sentence_function',
            field=models.PositiveIntegerField(choices=[(0, 'none'), (1, 'declarative'), (2, 'interrogative'), (3, 'exclamatory'), (4, 'imperative')], default=0, verbose_name='Sentence function'),
        ),
        migrations.AlterField(
            model_name='scenariolanguage',
            name='other_labels',
            field=models.CharField(blank=True, max_length=200, verbose_name='Allowed labels, comma-separated'),
        ),
    ]
