# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 13:54
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_auto_20190213_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='mds_labels_unique',
            field=picklefield.fields.PickledObjectField(editable=False, null=True, verbose_name=b'MDS unique labels'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='mds_weights',
            field=picklefield.fields.PickledObjectField(editable=False, null=True, verbose_name=b'MDS weights'),
        ),
    ]
