# Generated by Django 2.2.6 on 2020-01-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_auto_20191121_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariolanguage',
            name='use_labels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scenariolanguage',
            name='use_tenses',
            field=models.BooleanField(default=True),
        ),
    ]
