# Generated by Django 2.2.6 on 2020-01-15 00:08

from django.db import migrations


def migrate_use_other_label(apps, schema_editor):
    ScenarioLanguage = apps.get_model('stats', 'ScenarioLanguage')

    for sl in ScenarioLanguage.objects.all():
        sl.use_labels = sl.use_other_label
        sl.save()


def undo(apps, schema_editor):
    ScenarioLanguage = apps.get_model('stats', 'ScenarioLanguage')

    for sl in ScenarioLanguage.objects.all():
        sl.use_other_labels = sl.use_labels
        sl.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_auto_20200114_2353'),
    ]

    operations = [
        migrations.RunPython(migrate_use_other_label, undo),
    ]
