# Generated by Django 2.2.6 on 2020-01-15 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0014_scenario_use_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariolanguage',
            name='use_other_label',
        ),
    ]
