# Generated by Django 2.2.12 on 2020-06-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0035_labelkey_open_label_set'),
        ('stats', '0015_remove_scenariolanguage_use_other_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariolanguage',
            name='include_labels',
            field=models.ManyToManyField(blank=True, to='annotations.Label'),
        ),
    ]
