# Generated by Django 2.2.12 on 2020-06-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0017_scenario_other_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariolanguage',
            name='other_labels',
        ),
    ]
