# Generated by Django 2.2.12 on 2020-06-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0035_labelkey_open_label_set'),
        ('stats', '0018_remove_scenariolanguage_other_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariolanguage',
            name='include_keys',
            field=models.ManyToManyField(blank=True, to='annotations.LabelKey'),
        ),
    ]
