# Generated by Django 2.2.12 on 2020-06-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_scenariolanguage_include_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariolanguage',
            name='include_keys',
            field=models.ManyToManyField(blank=True, help_text='Keys selected here will be used as components of the fragment tuples.', related_name='_scenariolanguage_include_keys_+', to='annotations.LabelKey'),
        ),
        migrations.AlterField(
            model_name='scenariolanguage',
            name='include_labels',
            field=models.ManyToManyField(blank=True, help_text='Fragments will be included in the scenario only when they are assigned one of the selected labels. Leave emtpy to include all fragments.', related_name='_scenariolanguage_include_labels_+', to='annotations.Label', verbose_name='Filter by labels'),
        ),
    ]
