# Generated by Django 2.2.17 on 2021-02-19 14:22

from django.db import migrations

import numpy as np


class Migration(migrations.Migration):

    def normalize(apps, schema_editor):
        Scenario = apps.get_model('stats', 'Scenario')

        scenarios = []
        for s in Scenario.objects.exclude(last_run__isnull=True):
            # Set stress to 0 if the matrix is saved in an old format
            if not isinstance(s.mds_matrix, np.ndarray):
                s.mds_stress = None
            else:
                s.mds_stress = np.nan_to_num(np.sqrt(s.mds_stress / ((s.mds_matrix.ravel() ** 2).sum() / 2)))
            scenarios.append(s)

        Scenario.objects.bulk_update(scenarios, ['mds_stress'])

    dependencies = [
        ('stats', '0020_auto_20200626_1253'),
    ]

    operations = [
        migrations.RunPython(normalize),
    ]
