# Generated by Django 3.2.8 on 2021-10-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0022_scenario_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Publicly accessible (unauthenticated users)'),
        ),
    ]
