# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-20 12:32


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0005_auto_20180423_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selection_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='selection',
            name='selected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
