# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-02 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0006_auto_20180620_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='other_label',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
