# Generated by Django 2.2.6 on 2019-11-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0009_auto_20190529_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='is_no_target',
            field=models.BooleanField(default=False, verbose_name='This fragment does not contain a target'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='tense',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tense'),
        ),
    ]
