# Generated by Django 2.2.6 on 2020-01-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0031_auto_20200107_2217'),
        ('selections', '0010_auto_20191121_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='labels',
            field=models.ManyToManyField(to='annotations.Label'),
        ),
    ]
