# Generated by Django 2.2.6 on 2019-12-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0032_lables_data_migration'),
        ('selections', '0010_auto_20191121_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='labels',
            field=models.ManyToManyField(to='annotations.Label'),
        ),
    ]
