# Generated by Django 2.2.12 on 2020-06-27 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0035_labelkey_open_label_set'),
        ('selections', '0011_selection_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='tense_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotations.Tense'),
        ),
    ]
