# Generated by Django 2.2.12 on 2020-06-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0013_tense_char_to_foreign_key'),
    ]

    operations = [
        migrations.RenameField('Selection', 'tense', 'tense_old'),
        migrations.RenameField('Selection', 'tense_new', 'tense'),
    ]
