# Generated by Django 2.2.13 on 2020-07-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0014_rename_tense_new_to_tense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='tense_old',
        ),
    ]
