# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-20 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0024_corpus_tense_based'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='annotated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='tense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotations.Tense'),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='tense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotations.Tense'),
        ),
    ]
