# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-03 08:51


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0025_auto_20180620_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'permissions': (('edit_labels_in_interface', 'Can edit labels in the interface'),)},
        ),
        migrations.AlterField(
            model_name='annotation',
            name='tense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotations.Tense'),
        ),
    ]
