# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0025_auto_20180620_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragment',
            name='is_stative',
            field=models.BooleanField(default=False),
        ),
    ]
