# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-31 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0026_auto_20181003_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='upload',
            field=models.FileField(blank=True, upload_to=b'uploads/'),
        ),
    ]
