# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 15:07
from __future__ import unicode_literals

import annotations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0027_auto_20181123_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='xml_file',
            field=models.FileField(blank=True, upload_to=annotations.models.corpus_path),
        ),
    ]
