# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-12 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0028_source'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=[b'is_no_target', b'is_translation'], name='annotations_is_no_t_ea122e_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=[b'is_target'], name='annotations_is_targ_0e75c4_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=[b'is_target', b'sentence'], name='annotations_is_targ_c54455_idx'),
        ),
    ]
