# Generated by Django 2.2.6 on 2019-11-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0029_auto_20190912_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='is_no_target',
            field=models.BooleanField(default=False, verbose_name='The selected words in the original fragment do not form an instance of (a/an) <em>{}</em>'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='is_not_labeled_structure',
            field=models.BooleanField(default=False, verbose_name='The selected words in the original fragment are incorrectly marked as <em>{}</em>'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='is_not_same_structure',
            field=models.BooleanField(default=False, verbose_name='The translated fragment is not in the same structure (dialogue/narrative) as the original fragment'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='is_translation',
            field=models.BooleanField(default=True, verbose_name='This is a correct translation of the original fragment'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='check_structure',
            field=models.BooleanField(default=False, verbose_name='Check for formal structure in the Annotations'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='tense_based',
            field=models.BooleanField(default=True, verbose_name='Whether this Corpus is annotated for tense/aspect, or something else'),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='formal_structure',
            field=models.PositiveIntegerField(choices=[(0, 'none'), (1, 'narration'), (2, 'dialogue')], default=0, verbose_name='Formal structure'),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='sentence_function',
            field=models.PositiveIntegerField(choices=[(0, 'none'), (1, 'declarative'), (2, 'interrogative'), (3, 'exclamatory'), (4, 'imperative')], default=0, verbose_name='Sentence function'),
        ),
    ]
