# Generated by Django 2.2.6 on 2019-12-12 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0030_auto_20191121_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='tense_based',
            field=models.BooleanField(default=True, verbose_name='Check this to use tenses for annotation, Uncheck to configure lables'),
        ),
        migrations.CreateModel(
            name='LabelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=10)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_categories', to='annotations.Corpus')),
            ],
            options={
                'verbose_name_plural': 'Label Categories',
                'unique_together': {('corpus', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='annotations.LabelCategory')),
            ],
            options={
                'unique_together': {('category', 'title')},
            },
        ),
        migrations.AddField(
            model_name='annotation',
            name='labels',
            field=models.ManyToManyField(to='annotations.Label'),
        ),
        migrations.AddField(
            model_name='fragment',
            name='labels',
            field=models.ManyToManyField(to='annotations.Label'),
        ),
    ]
