# Generated by Django 2.2.6 on 2020-01-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0032_labels_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelkey',
            name='corpora',
            field=models.ManyToManyField(related_name='label_keys', to='annotations.Corpus'),
        ),
    ]
