# Generated by Django 2.2.6 on 2020-01-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0032_lables_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelcategory',
            name='color',
        ),
        migrations.AddField(
            model_name='label',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
