# Generated by Django 2.2.6 on 2020-04-06 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0033_auto_20200114_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotations.Language'),
        ),
        migrations.AddField(
            model_name='labelkey',
            name='language_specific',
            field=models.BooleanField(default=False, verbose_name='Labels are language specific'),
        ),
    ]
