# Generated by Django 2.2.6 on 2020-03-26 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0033_auto_20200114_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transliteration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotations.Word')),
            ],
        ),
    ]
