# Generated by Django 2.2.6 on 2020-04-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0034_auto_20200406_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelkey',
            name='open_label_set',
            field=models.BooleanField(default=True, verbose_name='Anyone can add new labels'),
        ),
    ]
