# Generated by Django 2.2.12 on 2020-06-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0035_labelkey_open_label_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='iso',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
