# Generated by Django 2.2.16 on 2020-09-21 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0036_auto_20200628_1427'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('key', 'language', 'title')},
        ),
    ]
