# Generated by Django 2.2.17 on 2020-11-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0037_auto_20200921_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['key', 'language', 'title']},
        ),
        migrations.AlterField(
            model_name='word',
            name='pos',
            field=models.CharField(max_length=200),
        ),
    ]
