# Generated by Django 2.2.17 on 2020-11-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0038_auto_20201103_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='random_next_item',
            field=models.BooleanField(default=True, verbose_name='Randomly select the next item for annotation'),
        ),
    ]
