# Generated by Django 2.2.20 on 2021-04-08 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0039_corpus_random_next_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragment',
            name='tense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotations.Tense'),
        ),
    ]
