# Generated by Django 3.2 on 2021-05-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0040_auto_20210408_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsentence',
            name='xml_id',
            field=models.CharField(blank=True, help_text='Leave blank to select all XML ids in the given Document', max_length=20),
        ),
    ]
